# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metodo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelCausa',
            new_name='Causa',
        ),
        migrations.RenameModel(
            old_name='ModelHallazgo',
            new_name='Hallazgo',
        ),
    ]
