# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metodo', '0002_auto_20180627_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agrupador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrupador', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='causa',
            name='agrupador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metodo.Agrupador'),
        ),
    ]
